index = "idx"
corpus = "line.toml"
dataset = "idx_data"
prefix = "."
stop-words = "stopwords.txt"
[[analyzers]]
	method = "ngram-word"
	ngram = 1
	[[analyzers.filter]]
		suppress-tags = true
		type = "icu-tokenizer"
	[[analyzers.filter]]
		type = "lowercase"
