prefix = "."
stop-words = "stopwords.txt"

dataset = "idx_data"
corpus = "line.toml"
index = "idx"


[[analyzers]]
method = "ngram-word"
ngram = 1
filter = [{type = "icu-tokenizer", suppress-tags = true}, {type = "lowercase"}]
